# Abschlussprojekt ProPra 2
Daniel Warkus; Jacques Pasquier; Robin Kraft; Jeff Nosbusch; Franz Hoffmann; Wolfgang Hinzmann; Oliver Nern; David Huseyin
v0.1, 11.02.2019
:toc:

## Festlegen von Syntaxregeln
Zu Beginn des Praktikums haben wir uns auf eine einheitliche Syntax geeinigt. Im
allgemeinen folgen wir dabei den bisher gelernten Coderichtlinien, die wir hier
nochmal zusammenfassen:

- Namen und Kommentare in Englisch
- Tabs anstelle von 4 Leerzeichen
- { hinter die Methode und nicht in eine neue Zeile
- Variablennamen: fooBar
- Methodennamen: FooBar

Zusätzlich wird zu erst eine funktionierende Datei in den `master`-Branch gepushed,
von dem alle zum arbeiten eigene Branches erstellen. Gemerged wird erst, sobald das
bearbeitete Problem volständig funktioniert, getestet und dokumentiert wurde.

## Planung
Unser Plan sieht es vor, 3 Self-contained-systems zu erstellen, die sich um die
Verwaltung der Daten von Benutzern, Atrikeln und Ausleihen kümmern und alle ihr
eigenes Mapping ausführen. Im Hintergrund soll dazu eine `Postgres`-Datenbank
laufen, auf die alle drei Systeme Zugriff haben.

## Dokumentation
### Artikel
Wir haben uns vorgestellt, dass die Anwendung `Article` die Artikel als Entitäten
in die Datenbank einfügt. Ein einzelner Artikel enthält die Variablen `articleID`,
`name`, `comment`, `PersonID`, `deposit`, `rent`, `available`, um die geforderten
Daten speichern zu können. Dies wurde mit den entsprechenden Annotationen implementiert.
Als nächstes wurde ein entsprechendes Repository `ArticleRepository` erstellt, dass
das CrudRepository extended, um die Funktionen ebendieses für das Mapping anwenden
zu können. Zuletzt folgte ein Controller `ArticleController`, der das Mapping für
die einzelnen Artikel übernimmt. Der Controller kann hier zwei verschiede Ansichten
erzeugen: eine Übersicht aller Atrikel unter `localhost:8080/article/`, die die einzelnen
Artikel mit ihren Namen, den Mietkosten und einem Link zur entsprechenden Detailansicht
des einzelnen Artikels darstellt, und die eben genannte Detailansicht, die alle
Variablen des Artikels außer der `articleID` darstellt, unter `localhost:8080/article/{id}`,
wobei {id} durch die `articleID` des Artikels ersetzt wird.

### Ausleihe
Eine Ausleihe ist eine eigene Entität namens 'Lending' diese beinhaltet die 'lendingId',
die 'lendingPerson' für die ausleihende Person und die 'lendedarticle', um die Artikel
in der Datenbank zu finden, weil diese die id von der ownerPerson besitzt die den Artikel anbietet.
Anfangs bekommt man eine Anfrage von der Artikelübersicht, und wird auf '/lendingRequest' weitergeleitet.
Dort kann man das 'startDate' und das 'endDate' eingeben wie lange die Ausleihe gehen soll.
Ebenfalls kann man einen 'requestComment' machen um sich für den Artikel zu bewerben.
Dann wird eine neue Entität angelegt, die 'Request' heißt. Diese speichert alle wichtigen Daten
um der Person die den Artikel anbietet eine Nachricht auf '/overview/{id}' zeigt, ob
sie die Anfrage auf den Artikel von der Person annehmen will.
Auf '/overviewLendings/{id}' kann sich die eingeloggte Person Ihre ausgeliehene Artikel anschauen,
hier wird eine Warnung ausgegeben falls die jetzige Zeit weiter ist als das 'endDate',
hier kann die Person auch auf 'return' drücken, damit der ausgeliehene Artikel 
wieder verfügbar wird und auf '/overviewBorrows/{id}' kann sich die eingeloggte
 Person Ihre angebotenen Artikel anschauen.
