# Abschlussprojekt ProPra 2
Daniel Warkus; Jacques Pasquier; Robin Kraft; Jeff Nosbusch; Franz Hoffmann; Wolfgang Hinzmann; Oliver Nern; David Huseyin
v0.1, 11.02.2019
:toc:

## Festlegen von Syntaxregeln
Zu Beginn des Praktikums haben wir uns auf eine einheitliche Syntax geeinigt. Im
allgemeinen folgen wir dabei den bisher gelernten Coderichtlinien, die wir hier
nochmal zusammenfassen:

- Namen und Kommentare in Englisch
- Tabs anstelle von 4 Leerzeichen
- { hinter die Methode und nicht in eine neue Zeile
- Variablennamen: fooBar
- Methodennamen: FooBar

Zusätzlich wird zu erst eine funktionierende Datei in den `master`-Branch gepushed,
von dem alle zum arbeiten eigene Branches erstellen. Gemerged wird erst, sobald das
bearbeitete Problem volständig funktioniert, getestet und dokumentiert wurde.

## Planung
Unser Plan sieht es vor, 3 Self-contained-systems zu erstellen, die sich um die
Verwaltung der Daten von Benutzern, Artikeln und Ausleihen kümmern und jeweils ihr
eigenes Mapping ausführen. Im Hintergrund soll dazu eine `Postgres`-Datenbank
laufen, auf die alle drei Systeme Zugriff haben und die die Daten speichert.

## Dokumentation
### Artikel
Wir haben uns vorgestellt, dass die Anwendung `Article` die Artikel als Entitäten
in die Datenbank einfügt. Ein einzelner Artikel enthält die Variablen `articleID`,
`name`, `comment`, `PersonID`, `deposit`, `rent`, `available`, um die geforderten
Daten speichern zu können. Dies wurde mit den entsprechenden Annotationen implementiert.
Als nächstes wurde ein entsprechendes Repository `ArticleRepository` erstellt, dass
das CrudRepository extended, um die Funktionen ebendieses für das Mapping anwenden
zu können. Danach folgte ein Controller `ArticleController`, der das Mapping für
die einzelnen Artikel übernimmt. Der Controller kann verschiede Ansichten erzeugen,
unter Anderem eine Übersicht über alle hochgeladenen Artikel und eine Detailansicht
ebendieser.

Zudem können Artikel bearbeitet werden. Dabei können lediglich die Attribute
`name`, `comment`, `deposit`, `rent` und `available` geändert werden, der Rest wird
vom alten Artikel automatisch übernommen.
Als erweiterte Features wurden dann noch ein paar Grundlagen implementiert, unter
anderem das Editieren von Artikeln sowie das Löschen. Zurzeit läuft dies noch ohne
ein Permissions-System, da dies erst mit Springboot-Security in einem späteren
Schritt hinzugefügt wird.

Desweiteren haben wir uns einem anspruchsvolleren Feature gewidmet: dem hinzufügen
von Bildern. Diese werden beim Erstellen dem Artikel hochgeladen und können weder
bearbeitet, noch gelöscht werden. Die Bilder sieht man dann in der Artikelübersicht.
Um das zu vollbringen haben wir das Bild erstmal als MultipartFile dem Artikel nicht
Persistent hinzugefügt, dann die wichtigen Informationen aus dem `File` ausgelesen
und in einer `Image` Klasse dafür gespeichert. Dem Artikel weisen wir dann in einer
`OnetoOne` Beziehung ein Image zu. In der Artikelansicht wird dann ein spezieller
Imagecontroller aufgerufen, der die Bytes des Bildes zurückgibt.

Als nächstes implementierten wir eine Suchfunktion, die einen `Query` entgegennimmt
und nach dem Vorkommen des Queries in den Namen und Beschreibungen der Artikel sucht.
Alle auf diese Weise gefundenen Artikel werden dann auf einer Übersichtsseite ausgegeben.
Die von uns implementierte Suche ist zudem Case-insensitive.

Zuletzt wurden Tests geschrieben, die einige Funktionen des Repositories und des
Controllers testen. So haben wir das Editieren von Artikeln und das Suchen nach
diesen getestet. Desweiteren haben wir einen Test zur `findById`-Funktion geschrieben
und einen weiteren zur `findByPersonId`-Funktion, wobei letztere alle Artikel einer
einzelnen Person zurückgeben soll.
