# Abschlussprojekt ProPra 2
Daniel Warkus; Jacques Pasquier; Robin Kraft; Jeff Nosbusch; Franz Hoffmann; Wolfgang Hinzmann; Oliver Nern; David Huseyin
v0.1, 11.02.2019
:toc:

## Festlegen von Syntaxregeln
Zu Beginn des Praktikums haben wir uns auf eine einheitliche Syntax geeinigt. Im
allgemeinen folgen wir dabei den bisher gelernten Coderichtlinien, die wir hier
nochmal zusammenfassen:

- Namen und Kommentare in Englisch
- Tabs anstelle von 4 Leerzeichen
- { hinter die Methode und nicht in eine neue Zeile
- Variablennamen: fooBar
- Methodennamen: FooBar

Zusätzlich wird zu erst eine funktionierende Datei in den `master`-Branch gepushed,
von dem alle zum arbeiten eigene Branches erstellen. Gemerged wird erst, sobald das
bearbeitete Problem volständig funktioniert, getestet und dokumentiert wurde.

## Planung
Unser Plan sieht es vor, 3 Self-contained-systems zu erstellen, die sich um die
Verwaltung der Daten von Benutzern, Atrikeln und Ausleihen kümmern und alle ihr
eigenes Mapping ausführen. Im Hintergrund soll dazu eine `Postgres`-Datenbank
laufen, auf die alle drei Systeme Zugriff haben.

## Dokumentation
### Artikel
Wir haben uns vorgestellt, dass die Anwendung `Article` die Artikel als Entitäten
in die Datenbank einfügt. Ein einzelner Artikel enthält die Variablen `articleID`,
`name`, `comment`, `PersonID`, `deposit`, `rent`, `available`, um die geforderten
Daten speichern zu können. Dies wurde mit den entsprechenden Annotationen implementiert.
Als nächstes wurde ein entsprechendes Repository `ArticleRepository` erstellt, dass
das CrudRepository extended, um die Funktionen ebendieses für das Mapping anwenden
zu können. Zuletzt folgte ein Controller `ArticleController`, der das Mapping für
die einzelnen Artikel übernimmt. Der Controller kann hier zwei verschiede Ansichten
erzeugen: eine Übersicht aller Atrikel unter `localhost:8080/article/`, die die einzelnen
Artikel mit ihren Namen, den Mietkosten und einem Link zur entsprechenden Detailansicht
des einzelnen Artikels darstellt, und die eben genannte Detailansicht, die alle
Variablen des Artikels außer der `articleID` darstellt, unter `localhost:8080/article/{id}`,
wobei {id} durch die `articleID` des Artikels ersetzt wird.

### User
Man kann sich einloggen, indem man seinen Username in das dafür vorgesehen Textfeld 
schreibt und den SignIn Button betätigt. Die einzige Vorraussetzung dafür ist,
dass bereits ein User mit diesem Usernamen in der Datenbank vorhanden ist.
Ansonsten kann man den SignUp Button betätigen, dann wird man weitergeleitet zu der SignIn Seite.
Hier kann man nun einen ganz neuen User erstellen, indem man alle Textfelder 
mit korrekten Eingaben ausfüllt un den entsprechenden Button betätigt.
Nach dem Einloggen bzw. dem Registrieren, kann man den ProfileOverview Button betätigen, 
dann wird man weitergeleitet auf eine Seite wo einem die Eigenen Profildaten in Textfeldern angezeigt werden.
In diese Textfelder kann man auch schreiben um seine Profil zu verändern. 
Um das Profil zu verändern füllt man einfach die Felder aus, bei welchen man die Daten
verändern will und betätigt den ApplyChanges Button, nun wurde das Profil in der datenbank aktualisiert.

##Testing
Wir haben viele Tests geschrieben und haben eine Overallline coverage von über 85% erreicht, 
Es werden alle Methoden in dem Controller getestet, wir erreichen keine 100% coverage, weil wir 
das Repository gemockt haben und in der Methode ins Repository gespeichert wird und in der gleichen methode
 wieder ausgelesen wenn wir die Methode für diesen Username mocken wird er schon ind er vorherigen methode abgefangen.   
