# Abschlussprojekt ProPra 2
Daniel Warkus; Jacques Pasquier; Robin Kraft; Jeff Nosbusch; Franz Hoffmann; Wolfgang Hinzmann; Oliver Nern; David Huseyin
v0.1, 11.02.2019
:toc:

## Festlegen von Syntaxregeln
Zu Beginn des Praktikums haben wir uns auf eine einheitliche Syntax geeinigt. Im
allgemeinen folgen wir dabei den bisher gelernten Coderichtlinien, die wir hier
nochmal zusammenfassen:

- Namen und Kommentare in Englisch
- Tabs anstelle von 4 Leerzeichen
- { hinter die Methode und nicht in eine neue Zeile
- Variablennamen: fooBar
- Methodennamen: FooBar

Zusätzlich wird zu erst eine funktionierende Datei in den `master`-Branch gepushed,
von dem alle zum arbeiten eigene Branches erstellen. Gemerged wird erst, sobald das
bearbeitete Problem volständig funktioniert, getestet und dokumentiert wurde.

## Planung
Unser Plan sieht es vor, 3 Self-contained-systems zu erstellen, die sich um die
Verwaltung der Daten von Benutzern, Artikeln und Ausleihen kümmern und jeweils ihr
eigenes Mapping ausführen. Im Hintergrund soll dazu eine `Postgres`-Datenbank
laufen, auf die alle drei Systeme Zugriff haben und die die Daten speichert.

## Dokumentation
### Artikel
Wir haben uns vorgestellt, dass die Anwendung `Article` die Artikel als Entitäten
in die Datenbank einfügt. Ein einzelner Artikel enthält die Variablen `articleID`,
`name`, `comment`, `PersonID`, `deposit`, `rent`, `available`, um die geforderten
Daten speichern zu können. Dies wurde mit den entsprechenden Annotationen implementiert.
Als nächstes wurde ein entsprechendes Repository `ArticleRepository` erstellt, dass
das CrudRepository extended, um die Funktionen ebendieses für das Mapping anwenden
zu können. Danach folgte ein Controller `ArticleController`, der das Mapping für
die einzelnen Artikel übernimmt. Der Controller kann verschiede Ansichten erzeugen,
unter Anderem eine Übersicht über alle hochgeladenen Artikel und eine Detailansicht
ebendieser.

Zudem können Artikel bearbeitet werden. Dabei können lediglich die Attribute
`name`, `comment`, `deposit`, `rent` und `available` geändert werden, der Rest wird
vom alten Artikel automatisch übernommen.
Als erweiterte Features wurden dann noch ein paar Grundlagen implementiert, unter
anderem das Editieren von Artikeln sowie das Löschen. Zurzeit läuft dies noch ohne
ein Permissions-System, da dies erst mit Springboot-Security in einem späteren
Schritt hinzugefügt wird.

Desweiteren haben wir uns einem anspruchsvolleren Feature gewidmet: dem hinzufügen
von Bildern. Diese werden beim Erstellen dem Artikel hochgeladen und können weder
bearbeitet, noch gelöscht werden. Die Bilder sieht man dann in der Artikelübersicht.
Um das zu vollbringen haben wir das Bild erstmal als MultipartFile dem Artikel nicht
Persistent hinzugefügt, dann die wichtigen Informationen aus dem `File` ausgelesen
und in einer `Image` Klasse dafür gespeichert. Dem Artikel weisen wir dann in einer
`OnetoOne` Beziehung ein Image zu. In der Artikelansicht wird dann ein spezieller
Imagecontroller aufgerufen, der die Bytes des Bildes zurückgibt.

Als nächstes implementierten wir eine Suchfunktion, die einen `Query` entgegennimmt
und nach dem Vorkommen des Queries in den Namen und Beschreibungen der Artikel sucht.
Alle auf diese Weise gefundenen Artikel werden dann auf einer Übersichtsseite ausgegeben.
Die von uns implementierte Suche ist zudem Case-insensitive.

Zuletzt wurden Tests geschrieben, die einige Funktionen des Repositories und des
Controllers testen. So haben wir das Editieren von Artikeln und das Suchen nach
diesen getestet. Desweiteren haben wir einen Test zur `findById`-Funktion geschrieben
und einen weiteren zur `findByPersonId`-Funktion, wobei letztere alle Artikel einer
einzelnen Person zurückgeben soll.


### User
Man kann sich einloggen, indem man seinen Username in das dafür vorgesehen Textfeld 
schreibt und den SignIn Button betätigt. Die einzige Vorraussetzung dafür ist,
dass bereits ein User mit diesem Usernamen in der Datenbank vorhanden ist.
Ansonsten kann man den SignUp Button betätigen, dann wird man weitergeleitet zu der SignIn Seite.
Hier kann man nun einen ganz neuen User erstellen, indem man alle Textfelder 
mit korrekten Eingaben ausfüllt un den entsprechenden Button betätigt.
Nach dem Einloggen bzw. dem Registrieren, kann man den ProfileOverview Button betätigen, 
dann wird man weitergeleitet auf eine Seite wo einem die Eigenen Profildaten in Textfeldern angezeigt werden.
In diese Textfelder kann man auch schreiben um seine Profil zu verändern. 
Um das Profil zu verändern füllt man einfach die Felder aus, bei welchen man die Daten
verändern will und betätigt den ApplyChanges Button, nun wurde das Profil in der datenbank aktualisiert.
##Testing
Wir haben viele Tests geschrieben und haben eine Overallline coverage von über 85% erreicht, 
Es werden alle Methoden in dem Controller getestet, wir erreichen keine 100% coverage, weil wir 
das Repository gemockt haben und in der Methode ins Repository gespeichert wird und in der gleichen methode
 wieder ausgelesen wenn wir die Methode für diesen Username mocken wird er schon ind er vorherigen methode abgefangen.   

### Ausleihe
Eine Ausleihe ist eine eigene Entität namens 'Lending' diese beinhaltet die 'lendingId',
die 'lendingPerson' für die ausleihende Person und die 'lendedarticle', um die Artikel
in der Datenbank zu finden, weil diese die id von der ownerPerson besitzt die den Artikel anbietet.
Anfangs bekommt man eine Anfrage von der Artikelübersicht, und wird auf '/lendingRequest' weitergeleitet.
Dort kann man das 'startDate' und das 'endDate' eingeben wie lange die Ausleihe gehen soll.
Ebenfalls kann man einen 'requestComment' machen um sich für den Artikel zu bewerben.
Dann wird eine neue Entität angelegt, die 'Request' heißt. Diese speichert alle wichtigen Daten
um der Person die den Artikel anbietet eine Nachricht auf '/overview/{id}' zeigt, ob
sie die Anfrage auf den Artikel von der Person annehmen will.
Auf '/overviewLendings/{id}' kann sich die eingeloggte Person Ihre ausgeliehene Artikel anschauen,
hier wird eine Warnung ausgegeben falls die jetzige Zeit weiter ist als das 'endDate',
hier kann die Person auch auf 'return' drücken, damit der ausgeliehene Artikel 
wieder verfügbar wird und auf '/overviewBorrows/{id}' kann sich die eingeloggte
 Person Ihre angebotenen Artikel anschauen.

