= Rhinoshare Application
:icons: font
:icon-set: octicon

== Wie starte ich die Anwendung ?

Zuerst muss das Programm von Github aus gecloned werden

`git clone git@github.com:hhu-propra2/abschlussprojekt-so-long-and-thanks-for-all-the-fish.git`

Dann in das richtige Verzeichnis

`cd abschlussprojekt-so-long-and-thanks-for-all-the-fish/`

Daraufhin lässt sich per Docker Compose das Programm, unsere Datenbank, sowie auch Propay starten.

`docker-compose up`

Auf folgender Website kommt man anschließend auf die Artikelübersicht, wo schon ein paar Artikel erstellt sind.

`localhost:8080/` oder `127.0.0.1:8080/`

Klickt man oben auf Einloggen, geht sofort die Login Seite auf. Dafür haben wir bereits im Databaseinitializer ein paar User erstellt. Alternativ kann man sich dort auch auf die `Neuen User erstellen`-Page redirecten lassen.

WARNING: Man kann dort nur User der Rolle `User` hinzufügen. Administatoren werden nur über den Databaseinitilizer erzeugt.

Viel Erfolg beim durchtesten.

=== User durch den Database Initializer

|=======
|Username |Password | Role
|`root1` |`1234` |ADMIN
|`root2` |`1234` |ADMIN
|`kMueller` |`1234` |USER
|`hFaust` |`1234` |USER
|`tineTree` |`1234` |USER
|`moosStein` |`1234` |USER
|=======

