version: "3.5"
services:
  rhinoshareapp:
    build:
      context: ./rhinoshareapp
      dockerfile: ./Dockerfile
    command: ["./wait-for-it.sh", "database:5432", "--", "java", "-jar", "app.jar"]
    ports:
      - "80:80"
    depends_on:
      - database
    networks:
      - web

  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=rhinoshare_default
      - POSTGRES_DB=database
      - POSTGRES_USER=rhinoshare
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - web

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:5555

networks:
  web:
    name: web
